export enum StatusNfeEnum {
  RASCUNHO = 'RASCUNHO',
  PROCESSANDO = 'PROCESSANDO',
  AUTORIZADA = 'AUTORIZADA',
  REJEITADA = 'REJEITADA',
  CANCELADA = 'CANCELADA',
  DENEGADA = 'DENEGADA',
  ERRO_ENVIO = 'ERRO_ENVIO',
}
